
spring:
  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for auto schema generation
    show-sql: true  # Enable SQL query logging
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/db_example
    username: khaitq
    password: password123_KHAI


